version: "3.9"

networks: 
  default:

services:
  frontend:
    build: "./frontend/svelte"
    container_name: "frontend"
    ports:
      - 5000:5000
    networks:
      default:
        aliases:
          - frontend
    links:
      - backend

  backend:
    build: "./backend"
    container_name: "backend"
    ports:
      - 8080:8080
    networks:
      default:
        aliases:
          - backend
